version: "2"
volumes:
  workdir:
  router_conf:
services:
  electron-intel:
    build: ./electron-intel
    privileged: true
    volumes:
      - "workdir:/usr/src/app/video/"
    labels:
      io.resin.features.dbus: "1"
      io.resin.features.kernel-modules: "1"
      io.resin.features.firmware: "1"
  balena-downloader:
    build: ./balena-downloader
    privileged: true
    ports:
      - "3000:3000"
    labels:
      io.resin.features.dbus: "1"
      io.resin.features.kernel-modules: "1"
      io.resin.features.firmware: "1"