version: "2"
volumes:
  workdir:
  downloader:
services:
  electron-intel:
    build: ./electron-intel
    privileged: true
    volumes:
      - "workdir:/usr/src/app/video/"
    labels:
      io.resin.features.dbus: "1"
      io.resin.features.kernel-modules: "1"
      io.resin.features.firmware: "1"
  fileupdate:
    build: ./balena-downloader
    privileged: true
    volumes:
      - "downloader:/usr/src/app/update_live/"
    ports:
      - "3000:3000"
    labels:
      io.resin.features.dbus: "1"
      io.resin.features.kernel-modules: "1"
      io.resin.features.firmware: "1"